# ─────────────────────────────
# Workspace Auto-Assign Rules
# ─────────────────────────────


# AI Workspace
windowrule = workspace 3, class:^(chrome-chatgpt.com__-Default)$
windowrule = workspace 3, class:^(chrome-claude.ai__.*-Default)$

# Chat workspace
windowrule = workspace 5, class:^(chrome-web.telegram.org__k_-Default)$
windowrule = workspace 5, class:^(org\.telegram\.desktop).*$
windowrule = workspace 5, class:^(chrome-web.whatsapp.com__-Default)$
windowrule = workspace 5, class:^(chrome-discord.com__app-Default)$
windowrule = workspace 5, class:^(chrome-discord.com__app-Default)$
windowrule = workspace 5 silent, class:^(chrome-teams.microsoft.com__v2_-Default)$
windowrule = workspace 5, class:com.github.IsmaelMartinez.teams_for_linux

windowrulev2 = float, class:(float-window)
windowrulev2 = center, class:(float-window)
windowrulev2 = size 800 600, class:(float-window)

# Make only "Snipper" and the unnamed Snipaste windows stay on top and focused
windowrulev2 = stayfocused, class:(Snipaste), title:(Snipper - Snipaste)
windowrulev2 = pin, class:(Snipaste), title:(Snipper - Snipaste)

# For the unnamed Snipaste window (just "Snipaste" as title)
windowrulev2 = stayfocused, class:(Snipaste), title:^(Snipaste)$
windowrulev2 = pin, class:(Snipaste), title:^(Snipaste)$

# Explicitly allow Paster to behave normally (optional, but makes intent clear)
windowrulev2 = unset, class:(Snipaste), title:(Paster - Snipaste)
